# Site settings
title: Iran University of Science and Technology (IUST)
course_name: Advanced Programming
course_description: "Advanced Programming in C#: This class focuses on Object Oriented programming in C#"
course_semester: "Spring 2019"
description: |
    Instructor: Sauleh Eetemadi

message: #Register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/ap97/" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io" # the base hostname & protocol for your site
githubdir: "username/repo"

# Author/user information
email: instructor-last-name@iust.ac.ir
twitter_username: sauleh_e 
github_username:  sauleh
authorurl: "http://sauleh.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins:
    - jekyll-jalali
